### ISSUE TITLE
该秘钥暴露会导致服务器被攻击,建议放入环境变量,同时加入gitignore,并关闭当前秘钥,重新生成新的秘钥

### ISSUE THREAD

**Issue by susanforme** [OMGWICK/food-sharing-community#2]
https://github.com/OMGWICK/food-sharing-community/blob/65adcdec23c43017a2c2823da8fcfde7ae9edcda/unploadCos.js#L10

**Comment by susanforme** [comment]
## 后端数据库秘钥,最好使用dotenv,放入环境变量

**Comment by OMGWICK** [comment]
> ## 后端数据库秘钥,最好使用dotenv,放入环境变量

太棒了！yyds！立即修复

**Comment by susanforme** [comment]
> > ## 后端数据库秘钥,最好使用dotenv,放入环境变量
> 
> 太棒了！yyds！立即修复

https://www.npmjs.com/package/dotenv
